// Generated by Selenium IDE
using OpenQA.Selenium;
using SeleniumGridTest;
using SeleniumGridTest.Factories;

[TestFixture]
public class AddProductToCartTest {
  string hubUrl;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  private readonly string PRODUCT_NAME = "1234";
  [SetUp]
  public void SetUp() {
    hubUrl = "http://localhost:4444/wd/hub";
    vars = new Dictionary<string, object>();
  }
  
  [Test]
  [Parallelizable]
  public void addProductToCart() {
    using (var driver = LocalDriverFactory.CreateInstance(BrowserType.Chrome, hubUrl))
    {
      driver.Navigate().GoToUrl("http://shop.qatl.ru/");
      driver.Manage().Window.Maximize();
      driver.FindElement(By.LinkText(PRODUCT_NAME)).Click();
      driver.FindElement(By.Name("quantity")).Click();
      driver.FindElement(By.Name("quantity")).SendKeys("5");
      driver.FindElement(By.Id("productAdd")).Click();

      Thread.Sleep(2000);

      Assert.AreEqual(driver.FindElement(By.XPath("//tr[1]//td[2]//a")).Text, PRODUCT_NAME);
    }
  }
  
  [Test]
  [Parallelizable]
  public void addProductToCart3() {
    using (var driver = LocalDriverFactory.CreateInstance(BrowserType.Firefox, hubUrl))
    {
      driver.Navigate().GoToUrl("http://shop.qatl.ru/");
      driver.Manage().Window.Maximize();
      driver.FindElement(By.LinkText(PRODUCT_NAME)).Click();
      driver.FindElement(By.Name("quantity")).Click();
      driver.FindElement(By.Name("quantity")).SendKeys("5");
      driver.FindElement(By.Id("productAdd")).Click();

      Thread.Sleep(2000);

      Assert.AreEqual(driver.FindElement(By.XPath("//tr[1]//td[2]//a")).Text, PRODUCT_NAME);
    }
  }
}
